package com.example.bank.dto;

import com.example.bank.enums.TransactionType;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@Builder
public class TransactionRequestDTO implements Serializable {

    @NotNull(message = "Transaction type is required.")
    private TransactionType transactionType;

    @Pattern(regexp = "^\\d{14}$", message = "Source account must be exactly 14 digits.")
    private String sourceAccount;

    @Pattern(regexp = "^\\d{14}$", message = "Destination account must be exactly 14 digits.")
    private String destinationAccount;

    @NotNull(message = "Amount is required.")
    @Min(value = 1, message = "Amount must be greater than zero.")
    private Integer amount;

    // Generated by server via TransactionTrackingCodeGenerator
    private String trackingCode;
}