spring:
  application:
    name: bank


  datasource:
    url: jdbc:oracle:thin:@localhost:5500/bank_pdb
    username: bank_user
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    user:
      name: admin1
      password: admin1pass

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

bank:
  account-number: 60606000060000
  transferFee:
    percentage: 0.1
    min-limit: 1000
    max-limit: 50000

logging:
  level:
    root: warn
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace