spring:
  application:
    name: bank


  datasource:
    url: jdbc:oracle:thin:@host.docker.internal:5500/bank_pdb
    username: bank_user
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest


app-security:
  default-admins:
    - username: "admin_1"
      password: "admin_pass_1"
      nationalCode: "1234567890"
      firstName: "name1"
      lastName: "namee1"
    - username: "admin_2"
      password: "admin_pass_2"
      nationalCode: "0987654321"
      firstName: "name2"
      lastName: "namee2"

bank:
  account-number: 60606000060000
  transferFee:
    percentage: 0.1
    min-limit: 1000
    max-limit: 50000


logging:
  level:
    root: info
    org:
      hibernate:
        orm:
          jdbc:
#            bind: trace